Fix autoloader path for PFCreateProperty
When Extension:SemanticMediaWiki is enabled, an autoloader error is
shown when accessing `Special:Special_Pages`:
```
Error: Failed opening required 'extensions/PageForms/includes/../specials/PF_CreateProperty.php
```

This was caused by https://github.com/wikimedia/mediawiki-extensions-PageForms/commit/b90e037d1e29c2d621231315e7497bf4bc1a979a

Bug: T425524


Change-Id: Id78a244ce752795d131bd16f353fa79b7ef133c1