Add RL dependency to "ext.pageforms.ooui.combobox"
This should avoid racing conditions, that causes errors like:

```
ReferenceError: pageforms is not defined
TypeError: pf.ComboBoxInput is not a constructor
```

Bug: T371607

Change-Id: Iffb2d5209e3bc96e5d45f6e4237fab0a6c76bd11